### ISSUE TITLE
The login link on the drawer is not shown

### ISSUE THREAD

**Issue by miyabitanimchi** [sh1mot4ku/GDS#55]
The login link on the drawer is not shown
<img width="319" alt="スクリーンショット 2021-12-31 午後11 38 08" src="https://user-images.githubusercontent.com/69213541/147846209-3286fb23-3a84-406f-b4c7-1329faab7818.png">
.

**Comment by BlackStone8960** [comment]
The reason: When styling header, someone deleted log in option from the drawer.
Solution: Added login option to drawer.
